# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do


# ensure_git_status_clean

# clear_derived_data

# spm(
#  command: "build",
#  build_path: "./build",
#  configuration: "release"
# )

 scan(
  workspace: "sevenCleanCode.xcworkspace",
  devices: ["iPhone 6s", "iPad Air"]
 )

 capture_ios_screenshots

  end
end
